# Generated by Django 6.0.5 on 2026-05-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0012_appointment_payment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('followup_days', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_followup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_record', to='appointments.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Medicine', 'Medicine'), ('Test', 'Test'), ('Procedure', 'Procedure'), ('Therapy', 'Therapy'), ('Instruction', 'Instruction')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('morning_before_breakfast', models.BooleanField(default=False)),
                ('morning_after_breakfast', models.BooleanField(default=False)),
                ('afternoon_before_lunch', models.BooleanField(default=False)),
                ('afternoon_after_lunch', models.BooleanField(default=False)),
                ('evening_before_snack', models.BooleanField(default=False)),
                ('evening_after_snack', models.BooleanField(default=False)),
                ('night_before_dinner', models.BooleanField(default=False)),
                ('night_after_dinner', models.BooleanField(default=False)),
                ('timing_guidance', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_items', to='consultations.consultationrecord')),
            ],
        ),
    ]
