# Generated by Django 6.0.5 on 2026-05-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrecord',
            name='followup_days',
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='followup_instruction',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
