# Generated by Django 6.0.5 on 2026-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_created_at_appointment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
