# Generated by Django 6.0.5 on 2026-05-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='daily_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
