# Generated by Django 6.0.5 on 2026-05-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_daily_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Waived', 'Waived'), ('Dues Pending', 'Dues Pending')], default='Pending', max_length=20),
        ),
    ]
