# Generated by Django 6.0.5 on 2026-05-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingTransaction',
        ),
    ]
