# Generated by Django 6.0.5 on 2026-05-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_delete_billingtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='appointment_proofs/'),
        ),
    ]
