# Generated by Django 6.0.5 on 2026-05-19 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0007_appointment_daily_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('Prescription', 'Prescription'), ('Report', 'Report'), ('Document', 'Document'), ('Patient Photo', 'Patient Photo')], max_length=30)),
                ('file', models.FileField(upload_to='patient_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to='appointments.appointment')),
            ],
        ),
    ]
