# Generated by Django 6.0.5 on 2026-05-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_delete_billingtransaction'),
        ('operations', '0001_initial'),
        ('patients', '0004_patient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Consultation', 'Consultation'), ('Medicine', 'Medicine'), ('Procedure', 'Procedure'), ('Emergency', 'Emergency'), ('Refund', 'Refund')], max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Dues Pending', 'Dues Pending'), ('Refunded', 'Refunded')], default='Pending', max_length=30)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer')], max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='billing_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
