# Generated by Django 6.0.5 on 2026-05-21 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_delete_billingtransaction'),
        ('operations', '0002_billingtransaction'),
        ('patients', '0004_patient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.CharField(max_length=100, unique=True)),
                ('visit_type', models.CharField(choices=[('OPD', 'OPD'), ('Revisit', 'Revisit'), ('Emergency', 'Emergency'), ('Manual', 'Manual')], default='OPD', max_length=50)),
                ('session_status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Due Pending', 'Due Pending'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_sessions', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_sessions', to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='billingtransaction',
            name='billing_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='operations.billingsession'),
        ),
    ]
