# Generated by Django 6.0.5 on 2026-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_billingsession_billingtransaction_billing_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtransaction',
            name='is_void',
            field=models.BooleanField(default=False),
        ),
    ]
