# Generated by Django 6.0.5 on 2026-05-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_appointment_payment_proof'),
        ('operations', '0005_billingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfile',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to='appointments.appointment'),
        ),
    ]
