# Generated by Django 6.0.5 on 2026-05-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_patientfile_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfile',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
