# Generated by Django 6.0.5 on 2026-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_patientfile_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtransaction',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
