# Generated by Django 6.0.5 on 2026-06-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_appointmentfollowup_patientcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentfollowup',
            name='followup_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
