# Generated by Django 6.0.5 on 2026-06-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_appointmentfollowup_followup_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='operations.appointmentfollowup')),
            ],
        ),
    ]
