# Generated by Django 6.0.5 on 2026-06-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_messagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('FOLLOWUP_BEFORE', 'FOLLOWUP_BEFORE'), ('FOLLOWUP_DUE', 'FOLLOWUP_DUE'), ('FOLLOWUP_OVERDUE', 'FOLLOWUP_OVERDUE'), ('CHRONIC_30', 'CHRONIC_30'), ('CHRONIC_60', 'CHRONIC_60'), ('CHRONIC_90', 'CHRONIC_90'), ('CHRONIC_120', 'CHRONIC_120')], max_length=50, unique=True)),
                ('whatsapp_template', models.TextField()),
                ('sms_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
