# Generated by Django 6.0.5 on 2026-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='provider_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
