# Generated by Django 6.0.5 on 2026-06-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_messagelog_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='template_type',
            field=models.CharField(choices=[('FOLLOWUP_BEFORE', 'FOLLOWUP_BEFORE'), ('FOLLOWUP_DUE', 'FOLLOWUP_DUE'), ('FOLLOWUP_OVERDUE_1', 'FOLLOWUP_OVERDUE_1'), ('FOLLOWUP_OVERDUE_3', 'FOLLOWUP_OVERDUE_3'), ('FOLLOWUP_OVERDUE_7', 'FOLLOWUP_OVERDUE_7'), ('CHRONIC_30', 'CHRONIC_30'), ('CHRONIC_45', 'CHRONIC_45'), ('CHRONIC_60', 'CHRONIC_60'), ('CHRONIC_90', 'CHRONIC_90'), ('CHRONIC_105', 'CHRONIC_105'), ('CHRONIC_120', 'CHRONIC_120'), ('CHRONIC_150', 'CHRONIC_150'), ('CHRONIC_180', 'CHRONIC_180'), ('CHRONIC_210', 'CHRONIC_210'), ('CHRONIC_240', 'CHRONIC_240'), ('CHRONIC_270', 'CHRONIC_270'), ('CHRONIC_300', 'CHRONIC_300'), ('CHRONIC_330', 'CHRONIC_330'), ('CHRONIC_365', 'CHRONIC_365')], max_length=50, unique=True),
        ),
    ]
