# Generated by Django 6.0.5 on 2026-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss'), ('Dr', 'Dr.'), ('Mx', 'Mx.')], max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Oth', 'Other')], max_length=10, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('disease', models.CharField(max_length=200, null=True)),
                ('appointment_date', models.DateField(null=True)),
            ],
        ),
    ]
