# Generated by Django 6.0.5 on 2026-05-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_paid_consultation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
