# Generated by Django 6.0.5 on 2026-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_allergies_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
