# Generated by Django 6.0.5 on 2026-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr', 'Dr.')], max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('General', 'General Physician')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
